import React, { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import DetailsResult from "../../components/details/DetailsResult";
import Button from "../../components/general/Button";
import ScreenNavigation from "../../components/general/ScreenNavigation";
import {
  appearances,
  firstNames,
  languageOptions,
  lastNames,
  misfortunes,
  traits,
} from "../../constants/constants";
import { characterBackgrounds } from "../../data/backgrounds";
import type {
  AbilityScores,
  Character,
  CharacterModifiers,
  ClassOptionsData,
  DiceState,
} from "../../types";
import { generateDescriptionTemplate, renderDescriptionTemplate, type DescriptionTemplate } from "../../utilities/DescriptionUtils";
import { detectGender, type Gender } from "../../utilities/GenderUtils";
import {
  chooseRandomItem,
  d,
  getWeightedValue,
} from "../../utilities/utilities";

interface CharacterDetailsProps {
  character: Character;
  setCharacter: (character: Character) => void;
  characterClass: Pick<ClassOptionsData, 'name' | 'languages'>;
  characterModifiers: Partial<CharacterModifiers>;
  abilityScores?: AbilityScores;
  dice?: DiceState;
  isMobile?: boolean;
}

export default function CharacterDetails(props: CharacterDetailsProps) {
  const {
    character,
    setCharacter,
    characterClass,
    characterModifiers,
    abilityScores,
    dice,
    isMobile,
  } = props;
  const { diceEnabled, diceService } = dice ?? {};

  const navigate = useNavigate();

  const [characterName, setCharacterName] = useState(character.name || "");
  const [alignment, setAlignment] = useState(character.alignment || "");
  const [appearance, setAppearance] = useState(character.appearance || "");
  const [personality, setPersonality] = useState(character.personality || "");
  const [background, setBackground] = useState(character.background || "");
  const [misfortune, setMisfortune] = useState(character.misfortune || "");
  const [description, setDescription] = useState(character.description || "");
  const [autoGeneratedDescription, setAutoGeneratedDescription] = useState(character.description || "");
  const [descriptionUserEdited, setDescriptionUserEdited] = useState(false);
  const descriptionUserEditedRef = useRef(false);
  const descriptionTextareaRef = useRef<HTMLTextAreaElement>(null);
  const [descriptionTemplate, setDescriptionTemplate] = useState<DescriptionTemplate | null>(null);
  const [gender, setGender] = useState<Gender>(
    (character.gender as Gender) ?? detectGender(character.name || "")
  );
  const [genderManuallySet, setGenderManuallySet] = useState(!!character.gender);
  const [languages, setLanguages] = useState(character.languages || []);
  const [languageSelected, setLanguageSelected] = useState("");
  const [languageCount, setLanguageCount] = useState<number>(0);
  const [classLanguageCount, setClassLanguageCount] = useState(0);
  const [hasLanguages, setHasLanguages] = useState(true);

  useEffect(() => {
    const languagesArr = characterClass.languages.split(",");

    if (languagesArr.length <= 2) {
      if (parseInt(characterModifiers.intelligenceModExtraLanguageCount ?? '0') < 1) {
        setHasLanguages(false);
      }
    } else {
      // first two langauges are not class-specific languages
      const classLanguageNumber = languagesArr.length - 2;
      setClassLanguageCount(classLanguageNumber);
      setLanguages(languagesArr);
    }
  }, []);

  useEffect(() => {
    setLanguageCount(
      parseInt(characterModifiers.extraLanguageCount ?? '0') +
        classLanguageCount -
        characterClass.languages.length,
    );
  }, [languages]);

  // Re-render the description whenever the name or pronouns change, as long
  // as a template has already been generated for this session.
  // Only update the visible description if the user has not manually edited it.
  useEffect(() => {
    if (!descriptionTemplate || !characterName) return;
    const rendered = renderDescriptionTemplate(descriptionTemplate, characterName, gender);
    setAutoGeneratedDescription(rendered);
    if (!descriptionUserEditedRef.current) {
      setDescription(rendered);
    }
  }, [characterName, gender, descriptionTemplate]);

  const handleNameChange = (event) => {
    const newName = event.currentTarget.value;
    setCharacterName(newName);
    if (!genderManuallySet) {
      setGender(detectGender(newName));
    }
  };

  const handleAlignment = (event) => {
    setAlignment(event.currentTarget.value);
  };

  const rollName = () => {
    const fullName = `${chooseRandomItem(firstNames)} ${chooseRandomItem(
      lastNames,
    )}`;
    setCharacterName(fullName);
    if (!genderManuallySet) {
      setGender(detectGender(fullName));
    }
  };

  const rollAppearance = () => {
    let appearanceArray = [...appearances];
    const num = 2;
    const selectedAppearances = [];
    for (let i = 0; i < num; i++) {
      const randomAppearance = chooseRandomItem(appearanceArray);
      selectedAppearances.push(randomAppearance);
      appearanceArray = appearanceArray.filter((k) => k !== randomAppearance);
    }

    setAppearance(selectedAppearances.join(", "));
  };

  const rollBackground = () => {
    const listLength = 100;

    if (isMobile || !diceEnabled || !diceService) {
      let diceResult = d(1, 100);
      let diceResult2 = d(1, 100);
      let background = getWeightedValue(characterBackgrounds, diceResult, 100);

      while (background?.includes("Roll for two skills")) {
        diceResult = d(1, 100);
        diceResult2 = d(1, 100);

        background = `${getWeightedValue(
          characterBackgrounds,
          diceResult,
          100,
        )}, ${getWeightedValue(characterBackgrounds, diceResult2, 100)}`;
      }

      setBackground(background);
      return;
    }

    if (!background.includes("Roll for two skills")) {
      diceService
        .show()
        .roll("1d100")
        .then((result) => {
          const value = result[0].value;

          if (isNaN(value)) {
            throw new Error("Dice result was not a number");
          }

          const newBackground = getWeightedValue(
            characterBackgrounds,
            value,
            listLength,
          );
          setBackground(newBackground);
        });
    }

    if (background.includes("Roll for two skills")) {
      diceService
        .show()
        .roll(["1d100", "1d100"])
        .then((result) => {
          const newBackground1 = getWeightedValue(
            characterBackgrounds,
            result[0].value,
            listLength,
          );
          const newBackground2 = getWeightedValue(
            characterBackgrounds,
            result[1].value,
            listLength,
          );
          const newBackgrounds = `${newBackground1}, ${newBackground2}`;
          setBackground(newBackgrounds);
        });
    }
  };

  const rollPersonality = () => {
    const num = 2;
    const selectedPersonalities = [];
    for (let i = 0; i < num; i++) {
      const randomTrait = chooseRandomItem(traits);
      selectedPersonalities.push(randomTrait);
    }

    setPersonality(selectedPersonalities.join(", "));
  };

  const rollMisfortune = () => {
    const randomMisfortune = chooseRandomItem(misfortunes);
    setMisfortune(randomMisfortune);
  };

  // Auto-resize the description textarea to fit its content whenever it changes.
  useEffect(() => {
    const el = descriptionTextareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${el.scrollHeight}px`;
  }, [description]);

  const handleDescriptionEdit = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setDescription(event.target.value);
    descriptionUserEditedRef.current = true;
    setDescriptionUserEdited(true);
  };

  const handleDescriptionRevert = () => {
    setDescription(autoGeneratedDescription);
    descriptionUserEditedRef.current = false;
    setDescriptionUserEdited(false);
  };

  const generateDescription = () => {
    if (!characterName) return;
    descriptionUserEditedRef.current = false;
    setDescriptionUserEdited(false);
    const template = generateDescriptionTemplate({
      className: characterClass.name,
      abilityScores: abilityScores ?? {
        strength: null,
        intelligence: null,
        wisdom: null,
        dexterity: null,
        constitution: null,
        charisma: null,
      },
    });
    setDescriptionTemplate(template);
  };

  const languageOption = (item) => {
    return (
      <option key={item} value={item}>
        {item}
      </option>
    );
  };

  const languagesList = () => {
    return languageOptions.map((item) => {
      return languageOption(item);
    });
  };

  const chooseLanguage = () => {
    setLanguageSelected(chooseRandomItem(languageOption));
  };

  const handleLanguageChange = (event) => {
    setLanguageSelected(event.target.value);
  };

  const addLanguage = () => {
    if (languages.includes(languageSelected) || languageSelected === "") {
      return;
    }
    setLanguages((oldArray) => [...oldArray, languageSelected]);
  };

  return (
    <React.Fragment>
      <div className="character-details-form">
        <label className="form-label form-label--name">
          <div className="form-text">Choose Name:</div>
          <input
            className="form-input"
            type="text"
            value={characterName}
            onChange={handleNameChange}
          />
          <button
            className="button button--random-name"
            onClick={rollName}
            type="button"
          >
            Random Name
          </button>
        </label>

        <div className="form-label form-label--gender">
          <div className="form-text">Pronouns:</div>
          <div className="gender-button-container">
            {(["male", "female", "neutral"] as Gender[]).map((g) => {
              const label = g === "male" ? "He/Him" : g === "female" ? "She/Her" : "They/Them";
              return (
                <button
                  key={g}
                  type="button"
                  className={
                    gender === g
                      ? "button button--gender button--gender--selected"
                      : "button button--gender"
                  }
                  onClick={() => { setGender(g); setGenderManuallySet(true); }}
                >
                  {label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="form-label form-label--alignment">
          <div className="form-text">Select Alignment:</div>

          <div className="alignment-button-container">
            <button
              type="button"
              value="lawful"
              className={
                alignment === "lawful"
                  ? "button button--alignment button--alignment--selected"
                  : "button button--alignment"
              }
              onClick={(e) => handleAlignment(e)}
            >
              Lawful
            </button>
            <button
              type="button"
              value="neutral"
              className={
                alignment === "neutral"
                  ? "button button--alignment button--alignment--selected"
                  : "button button--alignment"
              }
              onClick={(e) => handleAlignment(e)}
            >
              Neutral
            </button>
            <button
              type="button"
              value="chaotic"
              className={
                alignment === "chaotic"
                  ? "button button--alignment button--alignment--selected"
                  : "button button--alignment"
              }
              onClick={(e) => handleAlignment(e)}
            >
              Chaotic
            </button>
          </div>
        </div>

        <div className="form-label form-label--languages">
          <div className="form-text">
            {languageCount > 0
              ? `Additional Languages (${languageCount}):`
              : "Languages:"}{" "}
          </div>

          <div className="language-container">
            {`${alignment || "Alignment"}, Common${
              languages.length > 0 ? ", " + languages.join(", ") : ""
            }`}
          </div>

          {languageCount > 0 && (
            <div className="language-select-container">
              <select
                className="spells-select"
                value={languageSelected}
                onChange={handleLanguageChange}
              >
                <option value="" disabled>
                  Select Language
                </option>
                {languagesList()}
              </select>
              <button
                className="button--random-language"
                onClick={() => chooseLanguage()}
              >
                Random
              </button>
              <button
                className="button--add-language"
                onClick={() => addLanguage()}
              >
                Add
              </button>
            </div>
          )}
        </div>

        <div className="form-label form-label--optional-details">
          <div className="form-text">
            Optional Details
          </div>

          {!description && (
            <Button
              name="optional-details"
              callback={generateDescription}
              text={"Description"}
            ></Button>
          )}

          {description && (
            <div className="details-result details-result--description">
              <span className="details-result--name">Description:</span>
              <button
                type="button"
                className="button button--details-reroll"
                onClick={descriptionUserEdited ? handleDescriptionRevert : generateDescription}
              >
                {descriptionUserEdited ? "Revert" : "Reroll"}
              </button>
              <textarea
                ref={descriptionTextareaRef}
                className="details-result--data"
                value={description}
                onChange={handleDescriptionEdit}
              />
            </div>
          )}

          {!background && (
            <Button
              name="optional-details"
              callback={rollBackground}
              text={"Background (d100)"}
            ></Button>
          )}

          {background && (
            <DetailsResult
              name="Background Skill"
              value={background}
              callback={rollBackground}
            ></DetailsResult>
          )}

          {!appearance && (
            <Button
              name="optional-details"
              callback={rollAppearance}
              text={"Appearance"}
            ></Button>
          )}

          {appearance && (
            <DetailsResult
              name="Appearance"
              value={appearance}
              callback={rollAppearance}
            ></DetailsResult>
          )}

          {!personality && (
            <Button
              name="optional-details"
              callback={rollPersonality}
              text={"Personality"}
            ></Button>
          )}

          {personality && (
            <DetailsResult
              name="Personality"
              value={personality}
              callback={rollPersonality}
            ></DetailsResult>
          )}

          {!misfortune && (
            <Button
              name="optional-details"
              callback={rollMisfortune}
              text={"Misfortune"}
            ></Button>
          )}

          {misfortune && (
            <DetailsResult
              name="Misfortune"
              value={misfortune}
              callback={rollMisfortune}
            ></DetailsResult>
          )}
        </div>
      </div>

      <ScreenNavigation
        onPrev={() => {
          navigate('/equipment');
        }}
        prevLabel="Equipment"
        onNext={() => {
          navigate('/sheet');
        }}
        onNavigation={() => {
          setCharacter({
            ...character,
            name: characterName,
            alignment,
            appearance,
            background,
            personality,
            misfortune,
            description,
            gender,
            languages,
            hasLanguages,
          });
        }}
        nextLabel="Character Sheet"
        requirements={[
          !characterName && "Choose a name",
          !alignment && "Select an alignment",
        ].filter(Boolean)}
      />
    </React.Fragment>
  );
}
